spring:
  application:
    name: technical-library-service
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library_db
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: library
  kafka:
    bootstrap-servers:  localhost:9092
    producer:
      retries: 3
      properties:
        spring.json.trusted.packages:  '*'
      key-serializer:  org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
logging:
  level:
    org.hibernate: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.transaction: ERROR
    org.springframework.orm.jpa: ERROR

server:
  port: 8082

minio:
  endpoint: http://localhost:9000/
  user: admin
  password: adminpass
  bucketName: equipments
  maxFileSize: 2097152

